version: '3.3'

services:
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: db_${APP_NAME}
    hostname: db_${APP_NAME}
    ports:
      - '5432:5432'
    networks:
      - django-net
#
#  web:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: python ./manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/usr/src/app/
#    ports:
#      - '8000:8000'
#    env_file: .env
#    depends_on:
#      - db
#    hostname: ${APP_NAME}
#    container_name: ${APP_NAME}
#    restart: always
#    networks:
#      - django-net

volumes:
    postgres_data:

networks:
  django-net:
    driver: bridge
