# Generated by Django 4.0.3 on 2022-03-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='avatar',
            field=models.ImageField(default='images/default_avatar.png', upload_to='profile_images'),
        ),
    ]
