# Generated by Django 4.0.3 on 2022-03-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itology', '0002_client_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['user'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]
