name: Django CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m poetry config virtualenvs.create false
        python -m poetry install

    - name: Lint with Flake8
      run: |
        flake8 .

    - name: Run tests
      run: |
        pytest .

    - name: Checkout master
      uses: actions/checkout@v1

    - name: Add environment variables to .env
      run: |
        echo "DEBUG=0" >> .env
        echo "SQL_ENGINE=django.db.backends.postgresql" >> .env
        echo "DATABASE=postgres" >> .env
        echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
        echo "SQL_DATABASE=${{ secrets.SQL_DATABASE }}" >> .env
        echo "SQL_USER=${{ secrets.SQL_USER }}" >> .env
        echo "SQL_PASSWORD=${{ secrets.SQL_PASSWORD }}" >> .env
        echo "SQL_HOST=${{ secrets.SQL_HOST }}" >> .env
        echo "SQL_PORT=${{ secrets.SQL_PORT }}" >> .env

    - name: Build the images and start the containers
      run: |
        export GITHUB_WORKFLOW=True
        export MODE="Test"
        docker-compose -f docker-compose.yml build 
        docker-compose -f docker-compose.yml up -d

    - name: Stop containers
      if: always()
      run: docker-compose -f docker-compose.yml down
